<?php
$this->data['title'] = "John Hildred 1933-2013";
$this->layout("_layout.phtml");
?>
<!--
This is a slideshow, using some of my public images on flickr.
The good thing about the swapImage div is that it can contain anything and it will be swapped one for the other.
Only the first image is an actual image, the rest are anchors that get loaded the first time.
The .js code is somewhat modified gpl courtesy of TrendMedia Technologies, Inc., Brian McNitt.
-->
<div class="slideshow" style="height:800px">

	<div class="swapImage">
		<h1>Vow Renewal 2008</h1>
		<img src="http://farm6.staticflickr.com/5050/5258330902_800935ce32_z.jpg" />
	</div>
	<div class="swapImage" style="display: none">
		<h1>Blackstone Harbour</h1>
		<a
			href="http://farm3.staticflickr.com/2830/10636622654_e6c402312c_z_d.jpg"></a>
	</div>
	<div class="swapImage" style="display: none">
		<h1>Coleman</h1>
		<a
			href="http://farm6.staticflickr.com/5546/10636866303_179c9103f4_z_d.jpg"></a>
	</div>
	<div class="swapImage" style="display: none">
		<h1>Supper</h1>
		<a
			href="http://farm8.staticflickr.com/7417/10636641536_f4d0621236_z_d.jpg"></a>
	</div>
	<div class="swapImage" style="display: none">
		<h1>Lunch in the Backyard</h1>
		<a
			href="http://farm8.staticflickr.com/7408/10636643576_cf46e83ab8_z_d.jpg"></a>
	</div>
	<div class="swapImage" style="display: none">
		<h1>Credit River</h1>
		<a
			href="http://farm8.staticflickr.com/7386/10636872673_fd55bb00c4_z_d.jpg"></a>
	</div>
	<div class="swapImage" style="display: none">
		<h1>2 Grandpas with Aedan</h1>
		<a
			href="http://farm3.staticflickr.com/2867/10636874963_f67e7f2db1_z_d.jpg"></a>
	</div>
	<div class="swapImage" style="display: none">
		<h1>Looking Pleased</h1>
		<a
			href="http://farm6.staticflickr.com/5480/10636626185_e3fdd9c83d_z_d.jpg"></a>
	</div>
	<div class="swapImage" style="display: none">
		<h1>With Aedan Canoeing</h1>
		<a
			href="http://farm6.staticflickr.com/5473/10636653306_861fa4a31f_z_d.jpg"></a>
	</div>
	<div class="swapImage" style="display: none">
		<h1>Sparkly Water</h1>
		<a
			href="http://farm8.staticflickr.com/7364/10636630655_5d2bee0b23_z_d.jpg"></a>
	</div>
	<div class="swapImage" style="display: none">
		<h1>Brothers</h1>
		<a
			href="http://farm3.staticflickr.com/2865/10662105933_2269c9fbe7_z_d.jpg"></a>
	</div>
</div>
<div class="slideshow" style="height:800px">
	<div class="swapImage">
		<h1>Dad and Bovas</h1>
		<img
			src="http://farm3.staticflickr.com/2250/1524508774_93c0f4b027_z_d.jpg" />
	</div>

	<div class="swapImage" style="display: none">
		<h1>Christmas 2004</h1>
		<a
			href="http://farm1.staticflickr.com/129/396132921_5afe669d5d_z_d.jpg"></a>
	</div>

	<div class="swapImage" style="display: none">
		<h1>Ex 2005</h1>
		<a
			href="http://farm1.staticflickr.com/23/38338584_4fcae4c927_z_d.jpg?zz=1"></a>
	</div>

	<div class="swapImage" style="display: none">
		<h1>CNE 2004</h1>
		<a href="http://farm1.staticflickr.com/1/278783_9165eeac84_z_d.jpg"></a>
	</div>

	<div class="swapImage" style="display: none">
		<h1>At Our House</h1>
		<a
			href="http://farm3.staticflickr.com/2413/2488028610_2cd2ea477b_z_d.jpg"></a>
	</div>

	<div class="swapImage" style="display: none">
		<h1>Spring 2008</h1>
		<a
			href="http://farm1.staticflickr.com/243/449495408_a9d8cbba27_z_d.jpg?zz=1"></a>
	</div>

	<div class="swapImage" style="display: none">
		<h1>Spring 2012</h1>
		<a
			href="http://farm6.staticflickr.com/5310/5651332038_4f25c6645a_z_d.jpg"></a>
	</div>

	<div class="swapImage" style="display: none">
		<h1>East End 2010</h1>
		<a
			href="http://farm6.staticflickr.com/5088/5257757405_4c099ebd1e_z_d.jpg"></a>
	</div>
</div>
